ClassRoomRoutine/urls.py
from django.contrib import admin
from django.urls import path,include

admin.site.site_header = 'Class Room Routine'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('',include('main.urls'))

]

main/urls.py
from django.urls import path
from .views import *

app_name = 'main'
urlpatterns = [
    path('',login, name="login"),
    path('logout/',logout, name="logout"),
    path('home/',home, name="home"),
    path('routinelist/',routinelist,name="routinelist"),
    path('createroutine/',createroutine,name="createroutine"),
    path('deleteroutine/<int:routineid>/',deleteroutine,name="deleteroutine"),
]

main/models.py
from django.db import models
from django.utils import timezone

class ClassRoom(models.Model):
    classid = models.AutoField(primary_key=True)
    class_name = models.CharField(max_length=50,default='')
    

    def __str__(self):
        return self.class_name
    


class Subject(models.Model):
    sub_id = models.AutoField(primary_key=True)
    subject = models.CharField(max_length=100,default='')

    def __str__(self):
        return self.subject

class Teacher(models.Model):
    teacherid = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50,default='')
    phone = models.CharField(max_length=20,default='')
    location = models.CharField(max_length=100,default='')

    def __str__(self):
        return self.name

    
class ClassRoutine(models.Model):
    routineid =  models.AutoField(primary_key=True)
    ClassRoom = models.CharField(max_length=100,default='')
    start = models.CharField(max_length=100,default='')
    end = models.CharField(max_length=100,default='')
    subject =  models.CharField(max_length=100,default='')
    teacher =  models.CharField(max_length=100,default='')
    created_date = models.DateTimeField(default=timezone.now) 

    

main/views.py
from django.shortcuts import render,redirect
from .decorators import check_login,login_required
from django.contrib.auth import logout as auth_logout
from .models import *

@check_login
def login(request):
    return render(request,'login.html')


@login_required
def home(request):
    return render(request,'home.html')

@login_required
def logout(request):
    auth_logout(request)
    return redirect('main:login')

@login_required
def routinelist(request):
    routins = ClassRoutine.objects.all()
    context = {'routins':routins}
    return render(request,'routinLists.html',context)


@login_required
def createroutine(request):
    classrooms = ClassRoom.objects.all()
    teachers = Teacher.objects.all()
    subjects = Subject.objects.all()


    if request.method == 'POST':
        classroom = request.POST['class']
        teacher = request.POST['teacher']
        subject = request.POST['subject']
        start = request.POST['start']
        end = request.POST['end']
        isexist = ClassRoutine.objects.filter(ClassRoom=classroom,subject=subject,teacher=teacher,start=start,end=end)
        if not isexist:
            ClassRoutine.objects.create(ClassRoom=classroom,subject=subject,teacher=teacher,start=start,end=end)
            return redirect('main:routinelist')
    
    context = {
        'classrooms':classrooms,
        'teachers':teachers,
        'subjects':subjects
    }

    return render(request,'createroutine.html',context)


def deleteroutine(request,routineid):
    ClassRoutine.objects.filter(routineid=routineid).delete()
    return redirect('main:routinelist')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>{% block title%}{% endblock %}</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/TableExport/5.2.0/css/tableexport.css" integrity="sha512-+m+NCQG6uttXsLjwxHTUdhov99LW3TSFEiM2LSFMwfOePszb2as348/96cCBG35mOK+3Gp4P0EQRWpKLZfGTnA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <!-- Custom fonts for this template-->
  <link href="/static/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="/static/css/sb-admin-2.min.css" rel="stylesheet">
  <link href="/static/css/style.css" rel="stylesheet">

</head>

<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'main:home'%}">
        <div class="sidebar-brand-icon rotate-n-15">
          <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">PK School</div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Dashboard -->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'main:home'%}">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Dashboard</span></a>
      </li>
      

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        Interface
      </div>
      <li class="nav-item"><a class="nav-link" href="{% url 'main:routinelist'%}"><i class="fas fa-fw fa-cog"></i> <span>Create Routine </span> </a></li>

      
      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block">

      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

          <!-- Sidebar Toggle (Topbar) -->
          <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>

          
          <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">


            <div class="topbar-divider d-none d-sm-block"></div>

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{% if request.user.is_superuser %} {{user.username}} {% else %}{{user.socialaccount_set.all.0.extra_data.name }}{% endif %}</span>
                <img class="img-profile rounded-circle" src="{% if request.user.is_superuser %} /static/img/user.png {% else %}{{user.socialaccount_set.all.0.get_avatar_url}}{% endif %}" >
              </a>
              <!-- Dropdown - User Information -->
              <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                
                <a  class="dropdown-item logout" href="#" data-toggle="modal" data-target="#logoutModal">
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                  Logout
                </a>
              </div>
            </li>
            


          </ul>

        </nav>
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
          {% block content%}
          {% endblock %}

        </div>
        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->

      <!-- Footer -->
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Copyright &copy; Your Website 2021</span>
          </div>
        </div>
      </footer>
      <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="{% url 'main:logout' %}">Logout</a>
        </div>
      </div>
    </div>
  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="/static/vendor/jquery/jquery.min.js"></script>
  <script src="/static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  

  <!-- Core plugin JavaScript-->

  <!-- Custom scripts for all pages-->
  <script src="/static/js/sb-admin-2.min.js"></script>
  

</body>

</html>

templates/createroutine.html
{% extends 'base.html' %}
{% block title %} Create Routine {% endblock %}
{% block content %}
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Create new routines</h1>
</div>
<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-xl-7">
            <div class="card mb-4 mt-2 py-3 border-bottom-info ">
                <div class="card-body">
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-sm-5 col-xl-10">
                                <form class="user myTable" action="/createroutine/" method="POST">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <div class="form-group">
                                            <select name="class" required class="form-control">
                                                <option selected disabled>Select Class </option>
                                                {% for class in classrooms%}
                                                <option value="{{class.class_name}}">{{class.class_name}}</option>
                                                {% endfor %}
                                            </select>
                                        </div>
                                        <div class="form-group">
                                            <select name="subject" required class="form-control">
                                                <option selected disabled>Select Subject </option>
                                                {% for sub in subjects%}
                                                <option value="{{sub.subject}}">{{sub.subject}}</option>
                                                {% endfor %}
                                                <option value="launch break">launch break</option>
                                            </select>
                                        </div>
                                        <div class="form-group">
                                            <select name="teacher" required class="form-control">
                                                <option selected disabled>Select Teacher </option>
                                                {% for teacher in teachers%}
                                                <option value="{{teacher.name}}">{{teacher.name}}</option>
                                                {% endfor %}
                                                <option value="">-</option>
                                            </select>
                                        </div>
                                        <div class="form-group">
                                            <input type="time" required name="start" class="form-control" placeholder="Start time">
                                        </div>
                                        <div class="form-group">
                                            <input type="time" required name="end" class="form-control" placeholder="End time">
                                        </div>
                                        
                                        
                                    </div>
                                    <button  class="btn btn-primary btn-user text-lg btn-block" type="submit" id="createmaster" >
                                        Create 
                                      </button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% block title %} Home {% endblock %}
{% block content %}

{% endblock %}

templates/login.html
{% load socialaccount %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="/static/css/style.css">
</head>
<body>
    <div class="login-box">
        <a href="{% provider_login_url 'google' %}" class="social-button" id="google-connect"> <span>Login with Google</span></a>
    </div>
    
</body>
</html>

templates/routinLists.html
{% extends 'base.html' %}
{% block title %} Routin Lists {% endblock %}
{% block content %}
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Routine Lists</h1>
    <a href="{% url 'main:createroutine' %}"  class="d-sm-inline-block btn btn-sm btn-primary shadow-sm mt-2">Create new routine</a>
</div>

<div class="row justify-content-center mt-5">
    <div class="col justify-content-between">
        {% if routins%}
        <div class="col-xl-12">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                  <h6 class="m-0 font-weight-bold text-primary">List of Routines</h6>
                </div>
                <div class="card-body">
                    <div class="card-body">
                        <div class="table-responsive">
                          <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                              <tr>
                                <th>Class</th>
                                <th>Subject</th>
                                <th>Teacher</th>
                                <th>Start </th>
                                <th>End </th>
                                <th>Action</th>
                              </tr>
                            </thead>
                            
                            <tbody id="myTable">
                                {% for item in routins%}
                                    <tr>
                                        <td>{{item.ClassRoom}}</td>
                                        <td>{{item.subject}}</td>
                                        <td>{{item.teacher}}</td>
                                        <td>{{item.start}}</td>
                                        <td>{{item.end}}</td>
                                        
                                        <td>
                                            <a class="btn btn-danger btn-circle" href="{% url 'main:deleteroutine' item.routineid %}"><i class="fas fa-trash"></i></a>
                                        </td>
                                    </tr>
                                {% endfor %}
                              
                            </tbody>
                          </table>
                        </div>
                      </div>
                </div>
            </div>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}